---
#- hosts: servers
#remote_user: root
#become: yes
#become_method: sudo
#  roles:
#          - common
 #         - mysql_cluster_common

- hosts: mysql_cluster_mgm
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - common
  - mysql_cluster_common
  - mysql_cluster_mgm

- hosts: mysql_cluster_data
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - common
  - mysql_cluster_common
  - mysql_cluster_data
  #- mysql-cluster-data

- hosts: mysql_cluster_sql
  remote_user: root
  become: yes
  become_method: sudo
  roles:
  - common
  - mysql_cluster_common
  #- mysql_cluster_mgm
  - mysql_cluster_sql