---
- name: Update the Ubuntu system and services
  apt: update_cache=yes
  become: yes
- name: Install Basic Unix-level Services
  apt: name={{ item }} state=latest
  with_items:
  - python3
  - python3-pip
  - git
- name: change hosts
  template: src=hosts.j2 dest=/etc/hosts

- name: Set authorized key took from file
  authorized_key:
          user: ubuntu
          state: present
          key: "{{ lookup('file', './id_rsa.pub') }}"
- name: ensure private key and public one are present
  copy: 
    src: "./id_rsa" 
    dest: "/home/ubuntu/.ssh/id_rsa" 
    owner: ubuntu
    group: ubuntu
    mode: 0600
